# Given two timestamps of the same day: a number of hours, minutes and seconds for both of the timestamps. The moment of the first timestamp happened before the moment of the second one. Calculate how many seconds passed between them.
hour1=int(input())
min1=int(input())
s1=int(input())
hour2=int(input())
min2=int(input())
s2=int(input())
T1=int(hour1*3600+min1*60+s1)
T2=int(hour2*3600+min2*60+s2)
print(T2-T1)